# ***1.i***

In [ ]:
#importing files
from google.colab import files
uploaded=files.upload()

Saving A2Data_train.csv to A2Data_train.csv


In [ ]:
#loading the data into the data frame
import pandas as pd
data=pd.read_csv("A2Data_train.csv")
data.head()

0.58351  0.37939  0.83975  0.086861  0.61192  0.39203   0.18964   0.58509  \
0  0.86622  0.45135  0.93479   0.23581  0.50488  0.49742  0.117220  0.574880   
1  0.39142  0.91995  0.13873   0.99181  0.54367  0.98449  0.340260  0.206470   
2  0.79553  0.27854  0.22890   0.78929  0.49222  0.67084  0.769410  0.057104   
3  0.65223  0.96665  0.17985   0.35406  0.84042  0.92891  0.014597  0.229530   
4  0.71868  0.66333  0.29789   0.45105  0.42763  0.15868  0.932240  0.989020   

   0.89494   0.39385  ...  0.51706   0.20535   0.82999  0.24995   0.3198  \
0  0.71051  0.336890  ...  0.27412  0.460650  0.655440  0.56656  0.49062   
1  0.40131  0.128990  ...  0.27247  0.389110  0.799490  0.57753  0.86682   
2  0.20393  0.086936  ...  0.24901  0.659760  0.943350  0.41246  0.92715   
3  0.43920  0.548940  ...  0.93277  0.236740  0.027077  0.27111  0.23366   
4  0.65957  0.317730  ...  0.57039  0.067598  0.086989  0.59925  0.83566   

   0.19674   0.95855  0.84948  0.92369  1.9741  
0  0.19920  0.320680  0.41419  0.83023  2.3354  
1  0.69741  0.628630  0.29479  0.54280  2.2053  
2  0.11015  0.101310  0.66801  0.34573  2.0400  
3  0.56356  0.047289  0.62792  0.97930  2.2053  
4  0.89472  0.399830  0.32986  0.40907  2.7347  

[5 rows x 101 columns]

In [ ]:
data.shape

(9999, 101)

In [ ]:
#selecting the appropriate rows and columns for feature matrix and label vector
features= data.loc[ : , data.columns != '1.9741']
features.shape

(9999, 100)

In [ ]:
labels=data.loc[ : , data.columns== '1.9741']
labels.shape

(9999, 1)

In [ ]:
#converting our features and labels to numpy array for matrix computations
import numpy as np
x=np.array(features)
y=np.array(labels)

In [ ]:
#using the closed form expression to compute the coefficient vector w_ml
X=x.T
w_ml=(np.linalg.inv(X@x))@X@y
w_ml

array([[-7.85608335e-03],
       [-1.36527345e-02],
       [-3.67737525e-03],
       [ 2.71872276e-03],
       [ 1.88532246e-01],
       [ 2.66347307e-03],
       [ 9.52120980e-03],
       [ 1.79802299e-01],
       [ 3.67268262e-03],
       [ 4.99626642e-01],
       [ 8.43413736e-03],
       [ 4.24271355e-03],
       [ 1.41806051e-02],
       [ 3.97647665e-03],
       [ 9.37571465e-03],
       [-1.18622089e-03],
       [ 3.30600443e-03],
       [ 1.20858521e-03],
       [-9.33603241e-03],
       [-2.50056068e-03],
       [-1.17942517e-02],
       [-1.02122473e-02],
       [ 7.93607199e-03],
       [-1.00132333e-02],
       [ 6.04705154e-03],
       [-4.66242495e-03],
       [-3.03995989e-03],
       [ 8.22592082e-03],
       [ 1.20446086e-02],
       [-6.90391674e-03],
       [-8.57659635e-03],
       [ 1.07469316e-03],
       [ 4.94593951e-03],
       [ 5.93408484e-03],
       [-1.35584856e-02],
       [ 9.91088114e-04],
       [ 1.32037648e-02],
       [-1.14320115e-02],
       [-2.0

In [ ]:
#error in our case
((x@w_ml-y).T)@(x@w_ml-y)

array([[396.84416592]])

In [ ]:
#just visualising the individual error components
x@w_ml-y

array([[ 0.07866493],
       [-0.13650858],
       [ 0.08484774],
       ...,
       [-0.07854325],
       [ 0.17793524],
       [ 0.11408761]])

# ***1.ii***

In [ ]:
w=np.random.randn(100,1)
for i in range(1,150000):
  lr=0.00000001
  grad=2*(((X@X.T)@w)-X@y)
  w_new=w-lr*grad
  w=w_new

In [ ]:
2*(((X@X.T)@w)-X@y)

array([[ -99986.51092632],
       [-101949.66871955],
       [ -99113.72795857],
       [-102543.67458025],
       [-103224.39400032],
       [-100876.11748678],
       [ -99154.91443268],
       [-102387.57412137],
       [-100543.62269808],
       [-103749.44483327],
       [ -98491.29767705],
       [ -99462.89843131],
       [-100212.65364111],
       [ -98204.16998585],
       [-102045.07161309],
       [-102236.17722391],
       [-102989.12111873],
       [ -99907.49100844],
       [ -99717.62251132],
       [-105218.65734223],
       [ -98901.3917641 ],
       [-102374.9521094 ],
       [-102009.99802166],
       [-100389.17071235],
       [ -99786.87171152],
       [ -98127.79568022],
       [ -99967.20179651],
       [ -98868.28015527],
       [-102438.24643934],
       [ -98632.51143979],
       [-100428.76857912],
       [-101440.01617394],
       [-100149.21082221],
       [-104747.33982963],
       [ -99563.81164262],
       [-103434.74658736],
       [ -99306.08581421],
 

In [ ]:
w

array([[2481286.9844199 ],
       [2449486.75806185],
       [2481444.47805344],
       [2471091.93625981],
       [2446686.96290695],
       [2479192.59762025],
       [2423692.04668811],
       [2455855.03216312],
       [2446014.87956622],
       [2457987.5049743 ],
       [2468602.52431099],
       [2461692.00727066],
       [2463265.47576674],
       [2452838.34637633],
       [2467803.27878708],
       [2464807.11512262],
       [2464189.95303044],
       [2421407.16094222],
       [2441099.62646344],
       [2483373.17910906],
       [2472991.19884195],
       [2463922.45953154],
       [2443422.901897  ],
       [2456402.35545918],
       [2441840.98692589],
       [2453220.95505258],
       [2474970.22824402],
       [2470997.39569112],
       [2466432.53508655],
       [2455262.06700896],
       [2465896.63843982],
       [2487985.97860235],
       [2467347.73741706],
       [2490489.02043777],
       [2451403.94444075],
       [2477287.64337482],
       [2449556.26892822],
 